---
abstract: "wrapper class of Redis' key"
author:
  - 'Ichinose Shogo <shogo82148@gmail.com>'
build_requires:
  File::Temp: 0
  Redis: 0
  Test::Exception: 0
  Test::More: 0
  Test::RedisServer: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-Key
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Redis::Key:
    file: lib/Redis/Key.pm
    version: 0.01
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/shogo82148/Redis-Key/issues
  homepage: https://github.com/shogo82148/Redis-Key
  repository: git://github.com/shogo82148/Redis-Key.git
version: 0.01
